### ISSUE TITLE
Filament Sensor MK3 software does not update Z status

### ISSUE THREAD

**Issue by TimothyGold** [TheZeroBeast/MM-control-01#12]
I have been following your progress and the updates look awesome.  I just tried your last update but when loading your MK3 Filament Sensor firmware the Z status on the LCD in the from does not update and just has a ? next to the Z.  I defaulted the firmware and everything trying to get Z status to show.  Really hard to calibrate live Z without this but I was able to get first layer done to the point where I could give a MMU print a try.  It is going and so far way better success than with the default prusa.  So far with the Prusa firmware I have been about 1 for about 10.  Not very good.  I will keep you posted on success.  Thanks for all your help with this firmware.  
![20181110_141805](https://user-images.githubusercontent.com/13129318/48306861-424d7a00-e4fe-11e8-83fb-3aaf3c8aa665.jpg)
![20181110_142305](https://user-images.githubusercontent.com/13129318/48306862-437ea700-e4fe-11e8-9060-ca9e5fc3f0f7.jpg)

**Comment by TheZeroBeast** [comment]
Hi Timothy Gold,

This is due to not compiling with fprint enabled. Please follow readme.md instructions to enable.
If on Mac OS X let me know, and I'll direct you to the platform.txt file to update.

Step 3. under
> Development environment preparation

> 3. modify platform.txt to enable float printf support:
add "-Wl,-u,vfprintf -lprintf_flt -lm" to "compiler.c.elf.flags=" before existing flag "-Wl,--gc-sections"
example:
"compiler.c.elf.flags=-w -Os -Wl,-u,vfprintf -lprintf_flt -lm -Wl,--gc-sections"
