### ISSUE TITLE
Heated Bed Rapid Clicking

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#130]
Not sure how big an issue it is, but I hear the heated bed clicking rapidly (~5 hz?). It's not very loud but sitting near printer you definitely know it is happening.

I suspect it is louder than more recent stock firmware but it could be in my head. Not sure if there's meaningful data I can provide but if there's a test worth running let me know and I will.

**Comment by TheZeroBeast** [comment]
There will always be an associated noise when switching at 30Hz and due to poor PRUSA/Marlin code that calculates or more accurately doesn't calculate PID correctly you'll have strange small full on and off oscillations. You can minimise this for now by doing a 70c bed PID cal and updating your PIDs. I plan to redo the bed PID in the near future.

The low 30Hz is due to poor EINSY Board design as the MOSFET switching the bed doesn't get turned on hard enough to switch any higher without causing issues.

**Comment by AbeFM** [comment]
is it the same as Prusa's bed code?

I know some iterations they were wrecking hardware - I wanted to make sure
the clicking isn't that.

                  Thanks!
                          -Abe.

**Comment by TheZeroBeast** [comment]
No it's not the same, and they were wrecking hardware due to switching faster than the board MOSFET was setup to handle. I'm switching at the same 30Hz rate as their code so not issue.

Just double checked the bed with my scope to cheack, spot on.

![TEK0000 (2)](https://user-images.githubusercontent.com/20939095/64782385-63f91100-d5a8-11e9-87b8-220f9dfab6df.jpg)

**Comment by AbeFM** [comment]
Thanks for caring about the details!
