### ISSUE TITLE
Setting to switch between PINDA and BLTouch

### ISSUE THREAD

**Issue by Anonymus484** [TheZeroBeast/MM-control-01#222]
I have upgraded my Printer with the BLTouch-Probe (for non steel printbeds e.g. G10/FP4).
It workes great with some hickups here and there but over all i am happy so far.
But sometimes i wish to switch between the PINDA and the BLTouch in the Settings without reflashing the whole firmware.
Is it possible to integrate that feature in the future?

**Comment by TheZeroBeast** [comment]
Hello, due to limited resources this is not an option although I have been doing some speed and reliability tweaks that has it almost as quick as the PINDA and very reliable. These changes will be coming in release 4.0.2. If you would like to try a BETA release before then I can link a HEX, just let me know.
